### ISSUE TITLE
Create a `LaserDevice` initalisation GUI

### ISSUE THREAD

**Issue by mitchmindtree** [MindBuffer/smode_laser_plugin#25]
The OSC and Artnet devices present a nice GUI for specifying the initial parameters for their respective devices before they are initialised. It would be nice if we had something like this for the LASER device that allowed for specifying initial properties such as DAC point rate, target frame hz, optimisation configuration, etc.

**Comment by francis-maes** [comment]
There are two things:
  - the content of the DeviceIdentifier: this are parameters that are required in order to instantiate the Device and that can hardly be changed afterwards (that's actually what the Artnet device does)
  - Device variables: you can add any variable in your device and it will appear in the device configuration panel tree. I think that this is the method to prefer everytime possible, but this needs to values to be changeable while the device is running. 

In order to make the device variables working, they need to be oil objects and they need to be introspected (add a <variable> line in the xml).
Note: variables can be tagged as with `readonly="yes"` when they are return of information from the device that cannot be modified by the user (those variables will appear greyed in the UI).

**Comment by mitchmindtree** [comment]
Thanks for the advice! I believe all our LASER parameters can be updated while the stream is running, so device variables seem like the right choice :+1: I will close this in favour tracking remaining device GUI issues at #20.
